spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Shopping?createDatabaseIfNotExist=true
    username: root
    password: 12345
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      test-while-idle: true
      test-on-borrow: true
      max-conn-lifetime-millis: 15000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
